name: Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ${{ vars.TF_VAR_AWS_REGION }}
      TF_VAR_project_name: ${{ vars.TF_VAR_PROJECT_NAME }}
      TF_VAR_cidr_block: ${{ vars.TF_VAR_CIDR_BLOCK }}
      TF_VAR_public_subnet_cidrs: ${{ vars.TF_VAR_PUBLIC_SUBNET_CIDRS }}
      TF_VAR_private_subnet_cidrs: ${{ vars.TF_VAR_PRIVATE_SUBNET_CIDRS }}
      TF_VAR_availability_zones: ${{ vars.TF_VAR_AVAILABILITY_ZONES }}
      TF_VAR_my_ip: ${{ vars.TF_VAR_MY_IP }}

      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.TF_VAR_AWS_REGION }}

      - run: terraform init

      - run: terraform fmt

      - run: terraform fmt -check

      - run: terraform validate

      - run: terraform plan

      - run: terraform apply -auto-approve